#!/bin/bash
# Nome: Zhenlei Ji
# Email: zhenlei.ji@gmail.com
#
# Easy way to convert Unix time (seconds) to UTC time.
# 
# HOW TO USE
# Commands:
# ~$ ./todate [seconds]
#
# Example :
# ~$ ./todate 1476676336
if [ "$(uname)" == "Darwin" ]; then
    date -r $1 +'%Y-%m-%d %H:%M:%S'
else
    date --date="@$1"
fi
